name: First CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build using g++
        run: g++ main.cpp -o main -Werror -Wpedantic -Wall -Wextra
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: program
          path: main